### ISSUE TITLE
Can u define for which phpmyadmin version this theme can be applied 

### ISSUE THREAD

**Issue by Tanmay-Thanvi** [AIOFrame/phpMyAdmin#3]

**Comment by AIOFrame** [comment]
This is applicable for 4.9.1, I tried to implement for phpMyAdmin ver 5 but they completely changed the layouts. And i need some time to patiently work on this. I will try to do this in a week or two.

**Comment by Tanmay-Thanvi** [comment]
Phpmyadmin - 5.1.0
